[workflows] fix auto-update condition (#35)

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -12,8 +12,10 @@ env:
   GOLANGCI_LINT_VERSION: 'v1.62.0'
 
 jobs:
-  opencti-auto-update:
+  look-for-update:
     runs-on: ubuntu-latest
+    outputs:
+      update-available: ${{ steps.test-for-update.outputs.update-available }}
     steps:
       - uses: actions/checkout@v4
 
@@ -34,12 +36,38 @@ jobs:
           echo "Latest OpenCTI version: $NEXT_OPENCTI_VERSION"
 
       - name: Test if an update is available
+        id: test-for-update
         run: |
           if [ "$OPENCTI_VERSION" == "$NEXT_OPENCTI_VERSION" ]; then
             echo "GoCTI already supports latest OpenCTI version $NEXT_OPENCTI_VERSION"
+            echo "update-available=false" >> "$GITHUB_OUTPUT"
             exit 0
           fi
           echo "A new OpenCTI version $NEXT_OPENCTI_VERSION is available (GoCTI is currently supporting $OPENCTI_VERSION)"
+          echo "update-available=true" >> "$GITHUB_OUTPUT"
+
+  opencti-auto-update:
+    runs-on: ubuntu-latest
+    needs: look-for-update
+    if: needs.look-for-update.outputs.update-available == 'true'
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Get current OpenCTI version
+        run: |
+          OPENCTI_VERSION=$(sed -n 's/.*opencti\/platform:\(.*\)$/\1/p' ./docker-compose.yml | head -1)
+          echo "OPENCTI_VERSION=$OPENCTI_VERSION" >> "$GITHUB_ENV"
+          echo "Current OpenCTI version is $OPENCTI_VERSION"
+
+      - name: Fetch latest OpenCTI version
+        run: |
+          NEXT_OPENCTI_VERSION=$(curl -sL https://api.github.com/repos/OpenCTI-Platform/opencti/releases/latest | jq '.tag_name' | tr -d '"')
+          if [ -z $NEXT_OPENCTI_VERSION ]; then
+            echo "Could not get latest OpenCTI version"
+            exit 1
+          fi
+          echo "NEXT_OPENCTI_VERSION=$NEXT_OPENCTI_VERSION" >> "$GITHUB_ENV"
+          echo "Latest OpenCTI version: $NEXT_OPENCTI_VERSION"^
 
       - name: Fetch latest GoCTI version
         run: |
